name: acadprobot
channels:
  - defaults
  - conda-forge
dependencies:
  - annotated-types=0.7.0
  - anyio=4.9.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - async-timeout=4.0.3
  - bcrypt=3.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - certifi=2025.6.15
  - cffi=1.17.1
  - click=8.1.8
  - comm=0.2.2
  - cryptography=44.0.1
  - dataclasses-json=0.6.7
  - debugpy=1.8.11
  - decorator=5.2.1
  - dnspython=2.7.0
  - ecdsa=0.19.1
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - executing=2.2.0
  - fastapi=0.115.12
  - fastapi-cli=0.0.7
  - ffmpeg
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httptools=0.6.4
  - httpx=0.28.1
  - httpx-sse=0.4.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - langchain=0.3.26
  - langchain-community=0.3.27
  - langchain-core=0.3.68
  - langchain-text-splitters=0.3.8
  - langgraph=0.4.4
  - langgraph-checkpoint=2.0.21
  - langgraph-prebuilt=0.1.8
  - langgraph-sdk=0.1.72
  - langsmith=0.3.45
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20191231
  - libexpat=2.7.0
  - libffi=3.4.4
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.30
  - libsodium=1.0.20
  - libsqlite=3.45.2
  - libuv=1.50.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.7
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - marshmallow=3.26.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - msgpack-python=1.1.1
  - mypy_extensions=1.1.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openai=1.93.0
  - openssl=3.5.1
  - parso=0.8.4
  - passlib=1.7.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyasn1=0.4.8
  - pycparser=2.22
  - pydantic-settings=2.10.1
  - pygments=2.19.1
  - python=3.11.8
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-jose=3.4.0
  - python-multipart=0.0.20
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - rsa=4.9.1
  - setuptools=75.8.0
  - shellingham=1.5.4
  - six=1.17.0
  - sniffio=1.3.1
  - sqlite=3.45.2
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typer-slim=0.15.3
  - typer-slim-standard=0.15.3
  - typing-inspection=0.4.1
  - typing_inspect=0.9.0
  - uvloop=0.21.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xxhash=0.8.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.12
      - aiosignal==1.3.2
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - blis==1.3.0
      - catalogue==2.0.10
      - charset-normalizer==3.4.1
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - cymem==2.0.11
      - datasets==4.1.1
      - deprecation==2.1.0
      - dill==0.4.0
      - distro==1.9.0
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0.tar.gz
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - gotrue==2.12.0
      - greenlet==3.2.4
      - groq==0.20.0
      - hf-xet==1.1.3
      - httpcore==1.0.7
      - huggingface-hub==0.35.3
      - iniconfig==2.1.0
      - jiter==0.9.0
      - joblib==1.5.1
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain-huggingface==0.1.2
      - langchain-ollama==0.3.3
      - langchain-openai==0.3.14
      - langcodes==3.5.0
      - langdetect==1.0.9
      - language-data==1.3.0
      - loguru==0.7.3
      - lxml==5.4.0
      - marisa-trie==1.3.1
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - networkx==3.5
      - nomic==3.5.3
      - numpy==2.3.3
      - ollama==0.4.8
      - openpyxl==3.1.5
      - orjson==3.10.16
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandas==2.3.3
      - pgvector==0.4.1
      - pillow==11.2.1
      - playwright==1.55.0
      - pluggy==1.6.0
      - postgrest==1.0.2
      - praw==7.8.1
      - prawcore==2.4.0
      - preshed==3.0.10
      - propcache==0.3.2
      - psycopg2-binary==2.9.10
      - pyarrow==21.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyee==13.0.0
      - pyjwt==2.10.1
      - pymupdf==1.26.1
      - pysocks==1.7.1
      - pytest==8.4.0
      - pytest-mock==3.14.1
      - python-docx==1.1.2
      - pytz==2025.2
      - pyvector==0.1.3
      - realtime==2.4.3
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rich-toolkit==0.13.2
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - selenium==4.36.0
      - sentence-transformers==4.1.0
      - sentencepiece==0.2.0
      - smart-open==7.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.40
      - srsly==2.5.1
      - starlette==0.46.1
      - storage3==0.11.3
      - strenum==0.4.15
      - supabase==2.15.3
      - supafunc==0.9.4
      - sympy==1.14.0
      - tenacity==9.1.2
      - thinc==8.3.6
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.22.1
      - torch==2.7.1
      - tqdm==4.67.1
      - transformers==4.57.0
      - trio==0.31.0
      - trio-websocket==0.12.2
      - typer==0.15.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - update-checker==0.18.0
      - urllib3==2.5.0
      - uvicorn==0.34.0
      - wasabi==1.1.3
      - watchfiles==1.0.4
      - weasel==0.4.1
      - webdriver-manager==4.0.2
      - websocket-client==1.8.0
      - websockets==14.2
      - wrapt==1.17.3
      - wsproto==1.2.0
      - yarl==1.20.1
      - zstandard==0.23.0
